### ISSUE TITLE
TODOs:

### ISSUE THREAD

**Issue by JihoChoi** [JihoChoi/jihochoi#1]
### TODOs

- [ ] update collapsible sections
- [ ] organized papers review repository

**Comment by JihoChoi** [comment]
### TODO:
- [ ] [STATS 추가](https://github-readme-stats.vercel.app/api?username=jihochoi&show_icons=true&include_all_commits=true&theme=nord&hide_border=true)
